// Run only against isolated throwaway servers; see AGENTS.md.
import { passed } from './helpers.ts';
import { testSetup } from './setup.ts';
import { testChat } from './chat.ts';
import { testStreaming } from './streaming.ts';
import { testTreeMutations } from './tree-mutations.ts';
import { testMessageRanges } from './message-ranges.ts';
import { testCharacters } from './characters.ts';
import { testAvatars } from './avatars.ts';
import { testTemplates } from './templates.ts';
import { testPromptOverrides } from './prompt-overrides.ts';
import { testTools } from './tools.ts';
import { testImages } from './images.ts';
import { testGallery } from './gallery.ts';
import { testImageRevisions } from './image-revisions.ts';
import { testGenerationFailures } from './generation-failures.ts';
import { testRetries } from './retries.ts';
import { testSpeculation } from './speculation.ts';
import { testSpeculationLifecycle } from './speculation-lifecycle.ts';
import { testParallelSpeculation } from './parallel-speculation.ts';
import { testSearch } from './search.ts';
import { testCleanup } from './cleanup.ts';
import { testAuth } from './auth.ts';

const setup = await testSetup();
const chat = await testChat();
const streaming = await testStreaming(chat);
await testTreeMutations({ ...chat, ...streaming });
await testMessageRanges(chat);
const characters = await testCharacters(setup);
await testAvatars({ ...characters, ...setup });
const templates = await testTemplates({ ...chat, ...setup });
await testPromptOverrides({ ...templates, ...chat });
await testTools({ ...templates, ...chat });
const images = await testImages({ ...setup, ...templates, ...chat });
const gallery = await testGallery({ ...images, ...templates, ...setup });
const imageRevisions = await testImageRevisions({ ...templates, ...images, ...chat });
await testGenerationFailures({ ...templates, ...images, ...chat });
await testRetries({ ...templates, ...setup, ...chat });
await testSpeculation(chat);
const speculationLifecycle = await testSpeculationLifecycle(chat);
await testParallelSpeculation({ ...chat, ...speculationLifecycle });
await testSearch({ ...templates, ...setup });
await testCleanup({ ...images, ...gallery, ...imageRevisions, ...chat });
await testAuth({ ...setup, ...images, ...characters });

console.log(`\nALL ${passed} ASSERTIONS PASSED`);
